// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjkIuIVsOujBJaz3xMZ_H9rd1UMgDETw',
    appId: '1:367053382593:web:a3f785339e1bd398a80540',
    messagingSenderId: '367053382593',
    projectId: 'campus-archive-2f965',
    authDomain: 'campus-archive-2f965.firebaseapp.com',
    storageBucket: 'campus-archive-2f965.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQWSqwDt2LVl_7v6p98lRIj83OQClKjw',
    appId: '1:367053382593:android:c0c3f364229f2ef5a80540',
    messagingSenderId: '367053382593',
    projectId: 'campus-archive-2f965',
    storageBucket: 'campus-archive-2f965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nt4-kJfZ-8tZNByK8_bH3tbuP0h1wVA',
    appId: '1:367053382593:ios:1191de1ba5c33ee6a80540',
    messagingSenderId: '367053382593',
    projectId: 'campus-archive-2f965',
    storageBucket: 'campus-archive-2f965.firebasestorage.app',
    iosBundleId: 'com.example.campusArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nt4-kJfZ-8tZNByK8_bH3tbuP0h1wVA',
    appId: '1:367053382593:ios:1191de1ba5c33ee6a80540',
    messagingSenderId: '367053382593',
    projectId: 'campus-archive-2f965',
    storageBucket: 'campus-archive-2f965.firebasestorage.app',
    iosBundleId: 'com.example.campusArchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjkIuIVsOujBJaz3xMZ_H9rd1UMgDETw',
    appId: '1:367053382593:web:d4016a728b284002a80540',
    messagingSenderId: '367053382593',
    projectId: 'campus-archive-2f965',
    authDomain: 'campus-archive-2f965.firebaseapp.com',
    storageBucket: 'campus-archive-2f965.firebasestorage.app',
  );
}
